language: go

env:
  global:
    - GO111MODULE: "on"
    - GOFLAGS: "-mod=readonly"
    - GOPROXY: https://proxy.golang.org

go:
  - 1.13.x
  - tip

stages:
  - diff
  - test

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install: go get -u github.com/kyoh86/richgo

script:
  - richgo test -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)

after_success:
  - bash <(curl -s https://codecov.io/bash)
